apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: custom-metrics-sample-service
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/container-dependencies: "{app:[collector]}"
    spec:
      containers:
      - image: europe-central2-docker.pkg.dev/fourkeys-386218/run-otel/sample-metrics-app
        name: app
        ports:
        - containerPort: 8080
        env:
        - name: "OTEL_EXPORTER_OTLP_ENDPOINT"
          value: "http://localhost:4317"
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
      - image: europe-central2-docker.pkg.dev/fourkeys-386218/run-otel/otel-collector-metrics
        name: collector
        startupProbe:
          httpGet:
            path: /
            port: 13133
        resources:
          limits:
            cpu: 100m
            memory: 64Mi